#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nTurnRatio = 0, counter = 0, oddOrEven;
float currentSpeed = 20, angleU = 0;
const float angleBeta = (2*PI)*(180/PI), trackWidth = 120.0, diameter = 58.0, distanceS = (trackWidth * .5) * angleBeta;


task turn360(){

	while(true){

		/* This IF-STATEMENT will complete a 360 turn
		when a bump has occurred for 2.4 secs. Then it
		resetBumpedValue to 0*/
		if(getBumpedValue(touchSensor) == 1){
			counter ++;
			angleU = (distanceS *(2/diameter));

			/* Checks to see if the counter is even or odd.
			 * if odd, robot goes 360 counter-clockwise
			 * if even, robot goes 360 clockwise*/
			if(counter % 2 == 0){
				oddOrEven = 0;
				}else{
				oddOrEven = 1;
			}
			switch(oddOrEven){
			case 0:
				nTurnRatio = 50;
				sleep(4500);
				break;
			case 1:
				nTurnRatio = -50;
				sleep(4500);
				break;
			}
			resetBumpedValue(touchSensor);
		}// END OF IF-STATEMENT(getBumpedValue(touchSensor) == 1)
	}// END OF WHILE LOOP
}// END OF touchSensor

task main(){
	resetBumpedValue(touchSensor);
	angleU = 0;
	nTurnRatio = 0;
	startTask(turn360);
	while(true){
		setMotorSyncEncoder(RIGHT,LEFT,nTurnRatio,angleU,currentSpeed);
	}
}
