#pragma config(StandardModel, "EV3_REMBOT")
#pragma config(RenamedStdModelMotor, motorB, LEFT)
#pragma config(RenamedStdModelMotor, motorC, RIGHT)
#pragma config(RenamedStdModelSensor, S4, SONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float distanceCM;

task rangeSensorTASK(){

	while(true){
		distanceCM = getUSDistance(SONAR);
	}
}// END OF touchSensor

task display(){
	while(true){
		displayCenteredBigTextLine(3, "dist: %.2f cm", distanceCM);
	}//	END OF WHILE
}// END OF display


task main(){
	startTask(rangeSensorTASK);
	startTask(display);
	while(true){
		sleep(1);
	}
}
