#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int sensorValueS1;

task touchSensorTASK(){

	while(true){

		sensorValueS1 = getTouchValue(touchSensor);
	}
}// END OF touchSensor

task display(){
	while(true){
		switch(sensorValueS1){
		case 0:
			displayBigTextLine(1,"%s:","State");
			displayBigTextLine(3,"%s","RELEASED");
			break;
		case 1:
			displayBigTextLine(1,"%s:","State");
			displayBigTextLine(3,"%s","PRESSED");
			if(getTouchValue(touchSensor) == 0){
				displayBigTextLine(5,"%s: %i","BUMPED", getBumpedValue(touchSensor));
				resetBumpedValue(touchSensor);
				sleep(500);
				displayBigTextLine(5,"%s: %i","reset BUMPED", getBumpedValue(touchSensor));
			}
			break;
		}
	}//	END OF WHILE
}// END OF display


task main(){
	resetBumpedValue(touchSensor);
	startTask(touchSensorTASK);
	startTask(display);
	while(true){
		sleep(1);
	}
}
